2021-11-07 00:41:08,937 INFO    MainThread:40817 [internal.py:wandb_internal():87] W&B internal server running at pid: 40817, started at: 2021-11-07 00:41:08.937255
2021-11-07 00:41:08,938 DEBUG   HandlerThread:40817 [handler.py:handle_request():130] handle_request: run_start
2021-11-07 00:41:08,939 INFO    WriterThread:40817 [datastore.py:open_for_write():77] open: /home/cx/rmvision/yolov5-RM/wandb/offline-run-20211107_004108-12snnij8/run-12snnij8.wandb
2021-11-07 00:41:08,940 DEBUG   HandlerThread:40817 [meta.py:__init__():40] meta init
2021-11-07 00:41:08,940 DEBUG   HandlerThread:40817 [meta.py:__init__():54] meta init done
2021-11-07 00:41:08,940 DEBUG   HandlerThread:40817 [meta.py:probe():214] probe
2021-11-07 00:41:08,947 DEBUG   HandlerThread:40817 [git.py:repo():33] git repository is invalid
2021-11-07 00:41:08,947 DEBUG   HandlerThread:40817 [meta.py:_save_pip():58] save pip
2021-11-07 00:41:08,948 DEBUG   HandlerThread:40817 [meta.py:_save_pip():72] save pip done
2021-11-07 00:41:08,948 DEBUG   HandlerThread:40817 [meta.py:_save_conda():79] save conda
2021-11-07 00:41:09,977 DEBUG   HandlerThread:40817 [meta.py:_save_conda():89] save conda done
2021-11-07 00:41:09,977 DEBUG   HandlerThread:40817 [meta.py:probe():252] probe done
2021-11-07 00:41:11,537 DEBUG   HandlerThread:40817 [handler.py:handle_request():130] handle_request: shutdown
2021-11-07 00:41:11,537 INFO    HandlerThread:40817 [handler.py:finish():731] shutting down handler
2021-11-07 00:41:11,939 INFO    SenderThread:40817 [sender.py:finish():1091] shutting down sender
2021-11-07 00:41:12,537 INFO    WriterThread:40817 [datastore.py:close():281] close: /home/cx/rmvision/yolov5-RM/wandb/offline-run-20211107_004108-12snnij8/run-12snnij8.wandb
2021-11-07 00:41:12,539 INFO    MainThread:40817 [internal.py:handle_exit():77] Internal process exited
